### ISSUE TITLE
Initial Run - 502 Gateway Error (MacOS)

### ISSUE THREAD

**Issue by nifa-dev** [cnizzardini/cakephp-docker#13]
I just cloned this repository for the first time to my local system.  I'm rusty, just trying to get back into tinkering.  Docker gets a good reputation for getting an environment up quickly.

Most seems to go well, but I get a 502 Error when trying to access the initial page.  

It looks like one (php) of the three containers in this app doesn't start, or it exits immediately I should say.  

This is the log from starting up the container:

php_1 | Installing dependencies from lock file (including require-dev)
php_1 | Verifying lock file contents can be installed on current platform.
php_1 | Nothing to install, update or remove
php_1 | Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.
php_1 | Generating autoload files
php_1 | 56 packages you are using are looking for funding.
php_1 | Use the `composer fund` command to find out more!
php_1 | > App\Console\Installer::postInstall
php_1 | No Security.salt placeholder to replace.
php_1 | setfacl: logs: Not supported
nifa-scoring-40_php_1 exited with code 1

Any thoughts?  It seems like the php container isn't starting successfully, perhaps with the setfacl command.  

I'll keep digging into it...but thought I'd post here.

**Comment by cnizzardini** [comment]
Could be this: https://github.com/cnizzardini/cakephp-docker/issues/10 

I've been working on some other projects and haven't be able to give this one any love recently.

**Comment by cnizzardini** [comment]
Yeah I get the same thing running on a Mac. I don't have access to my usual linux desktop at the moment where I do most of my development.

**What operating system are you using?**

In the interim, commenting out all `setfacl` lines in `docker-entrypoint.sh` got the containers to come up for me.

**Comment by nifa-dev** [comment]
Sorry, running on Mac.  

I commented out the setfacl lines as you suggested and the container comes up for me too.

**Comment by cnizzardini** [comment]
There are a few things to clean up in MacOS that i'll commit later today:

#### Fixing emoji display: 

1. Change `SHELL`:

```makefile
SHELL 			:= /bin/bash # set shell based on host os, use /bin/zsh for mac
```

Before when running `make`:

```console
\U1F370  CakePHP Docker (unofficial) \U203A https://github.com/cnizzardini/cakephp-docker 
```

After:

```console
🍰  CakePHP Docker (unofficial) › https://github.com/cnizzardini/cakephp-docker 
```

#### Fixing setfacl issues

In the `Makefile` add new `HOST_OS` build-arg:

```makefile
#
# install command
#
init: do.copy
	@printf $(DOCKER_ICO) && printf "$(GOOD)running docker build and up $(E)"
	@mkdir -p app && touch app/.gitkeep
	@docker-compose build --build-arg UID=$(shell id -u) --build-arg ENV=dev --build-arg HOST_OS=$(uname -s)
	@$(DC_UP)
init.nocache: do.copy
	@printf $(DOCKER_ICO) && printf "$(GOOD)running docker build --no-cache and up $(E)"
	@mkdir -p app && touch app/.gitkeep
	@docker-compose build --build-arg UID=$(shell id -u) --build-arg ENV=dev --no-cache --build-arg HOST_OS=$(uname -s)
	@$(DC_UP)
```

In the `Dockerfile` add a new `ENV`:

```dockerfile
ENV HOST_OS=$HOST_OS
```

In `php/docker-entrypoint.sh` add a condition for Linux: 

```sh
  if ["$HOST_OS" = 'Linux']; then
        setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX logs
        setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX tmp
        setfacl -R -m g:nginx:rwX /srv/app
  fi
```

It seems `setafcl` will not run on volumes bound to Mac. There is a probably a better way to do this.

@nifa-dev if you want to be a second set of eyes on verifying these changes that would be great.

**Comment by cnizzardini** [comment]
Also an issue with `sed` which is used by `make xdebug.on` and `make xdebug.off`.

```console
brew install gnu-sed
```

Change `sed` commands to `gsed` in your `Makefile`

**Comment by Gandolf90** [comment]
tested today your mac-fix 
mac-test-php-1  | 22 package suggestions were added by new dependencies, use `composer suggest` to see details.
mac-test-php-1  | Generating autoload files
mac-test-php-1  | 55 packages you are using are looking for funding.
mac-test-php-1  | Use the `composer fund` command to find out more!
mac-test-php-1  | PHP CodeSniffer Config installed_paths set to ../../cakephp/cakephp-codesniffer,../../slevomat/coding-standard
mac-test-php-1  | > App\Console\Installer::postInstall
mac-test-php-1  | Created `config/app_local.php` file
mac-test-php-1  | Created `/srv/app/logs` directory
mac-test-php-1  | Created `/srv/app/tmp/cache/views` directory
mac-test-php-1  | Permissions set on /srv/app/tmp/cache/views
mac-test-php-1  | Permissions set on /srv/app/logs
mac-test-php-1  | Updated Security.salt value in config/app_local.php
mac-test-php-1  | Installing dependencies from lock file (including require-dev)
mac-test-php-1  | Verifying lock file contents can be installed on current platform.
mac-test-php-1  | Nothing to install, update or remove
mac-test-php-1  | Generating autoload files
mac-test-php-1  | 55 packages you are using are looking for funding.
mac-test-php-1  | Use the `composer fund` command to find out more!
mac-test-php-1  | > App\Console\Installer::postInstall
mac-test-php-1  | Updated Security.salt value in config/app_local.php
mac-test-php-1  | setfacl: logs: Not supported
mac-test-php-1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)

same error

**Comment by Gandolf90** [comment]
> tested today your mac-fix mac-test-php-1 | 22 package suggestions were added by new dependencies, use `composer suggest` to see details. mac-test-php-1 | Generating autoload files mac-test-php-1 | 55 packages you are using are looking for funding. mac-test-php-1 | Use the `composer fund` command to find out more! mac-test-php-1 | PHP CodeSniffer Config installed_paths set to ../../cakephp/cakephp-codesniffer,../../slevomat/coding-standard mac-test-php-1 | > App\Console\Installer::postInstall mac-test-php-1 | Created `config/app_local.php` file mac-test-php-1 | Created `/srv/app/logs` directory mac-test-php-1 | Created `/srv/app/tmp/cache/views` directory mac-test-php-1 | Permissions set on /srv/app/tmp/cache/views mac-test-php-1 | Permissions set on /srv/app/logs mac-test-php-1 | Updated Security.salt value in config/app_local.php mac-test-php-1 | Installing dependencies from lock file (including require-dev) mac-test-php-1 | Verifying lock file contents can be installed on current platform. mac-test-php-1 | Nothing to install, update or remove mac-test-php-1 | Generating autoload files mac-test-php-1 | 55 packages you are using are looking for funding. mac-test-php-1 | Use the `composer fund` command to find out more! mac-test-php-1 | > App\Console\Installer::postInstall mac-test-php-1 | Updated Security.salt value in config/app_local.php mac-test-php-1 | setfacl: logs: Not supported mac-test-php-1 exited with code 1 ^CGracefully stopping... (press Ctrl+C again to force)
> 
> same error

checked branch in new folder - that completely new folder worked for me!

**Comment by cnizzardini** [comment]
I need to add a note that if you want to do a complete "reinstall" the steps are:

```console
rm -rf app
mkdir app
make init
```

That sets things back to how it is when you first clone the repo, minus all the docker images now pulled down on your system.
