### ISSUE TITLE
Deploying to AWS ECS

### ISSUE THREAD

**Issue by jakubplus** [cnizzardini/cakephp-docker#26]
Hi,
this is not an issue but more of a question regarding the deployment usage.

I'm trying to deploy the setup to AWS Elastic Container Service.
I have a sufficient permissions on AWS IAM and a docker context created.

While executing 
`docker compose up`
I'm getting:
`WARNING services.build: unsupported attribute`
`WARNING services.scale: unsupported attribute`
`ECS Fargate does not support bind mounts from host: incompatible attribute`

Are you able to help me on this to fix mounts into acceptable by ECS Fairgate?

**Comment by cnizzardini** [comment]
I haven't worked with aws fargate before. I generally just use this project for local development TBH.

**Comment by jakubplus** [comment]
Ok thanks for the information.
